In [15]:
import pandas as pd
import numpy as np

In [16]:
yangin_istatistik = pd.read_csv(r"C:\Users\terzi\Desktop\TEMİZ\yangin_istatistik\2018\142_202203_2018yanginistatistik.csv", sep=";")

In [17]:
yangin_istatistik.head()

,ilceler,elk._kontak,lpg_d.gaz_vb.,ocak_sob._kalo._kaz.,baca_tut.,sig._ve_kibr.,akary.,pat._madd.,yıld._dus.,sabotaj,diger,anlasılamadı,tplm
0,SELÇUKLU,85,6,12,15,730,11,2,0,21,82,4,968
1,MERAM,84,6,38,12,502,7,3,1,12,44,6,715
2,KARATAY,90,6,27,10,802,5,0,0,21,56,10,1027
3,SANCAK,0,0,0,0,0,0,0,0,0,0,0,0
4,AKÖREN,6,0,0,2,19,0,0,1,0,45,2,75

In [18]:
yangin_istatistik = yangin_istatistik.rename(columns={'elk._kontak': 'elektrik_kontagi', 'lpg_d.gaz_vb.': 'lpg/dogalgaz', 'ocak_sob._kalo._kaz.': 'ocak/soba/kalorifer/kazan', 'baca_tut.': 'baca_tutusmasi', 'sig._ve_kibr.': 'sigara/kibrit', 'akary.': 'akaryakit', 'pat._madd.': 'patlayici_madde', 'yıld._dus.': 'yildirim_dusmesi', 'anlasılamadı': 'anlasilamadi', 'tplm': 'toplam'})

In [19]:
yangin_istatistik.head()

,ilceler,elektrik_kontagi,lpg/dogalgaz,ocak/soba/kalorifer/kazan,baca_tutusmasi,sigara/kibrit,akaryakit,patlayici_madde,yildirim_dusmesi,sabotaj,diger,anlasilamadi,toplam
0,SELÇUKLU,85,6,12,15,730,11,2,0,21,82,4,968
1,MERAM,84,6,38,12,502,7,3,1,12,44,6,715
2,KARATAY,90,6,27,10,802,5,0,0,21,56,10,1027
3,SANCAK,0,0,0,0,0,0,0,0,0,0,0,0
4,AKÖREN,6,0,0,2,19,0,0,1,0,45,2,75

In [20]:
a=yangin_istatistik["elektrik_kontagi"]
b=yangin_istatistik["lpg/dogalgaz"]
c=yangin_istatistik["ocak/soba/kalorifer/kazan"]
d=yangin_istatistik["baca_tutusmasi"]
e=yangin_istatistik["sigara/kibrit"]
f=yangin_istatistik["akaryakit"]
g=yangin_istatistik["patlayici_madde"]
h=yangin_istatistik["yildirim_dusmesi"]
i=yangin_istatistik["sabotaj"]
j=yangin_istatistik["diger"]
k=yangin_istatistik["anlasilamadi"]
l=yangin_istatistik["toplam"]

toplam_saglama=a+b+c+d+e+f+g+h+i+j+k==l

In [21]:
yangin_istatistik.to_csv(r"C:\Users\terzi\Desktop\yangin_istatistik\2018\csv\yangin_sayi_ve_sebepleri_2018.csv" ,index=False ,header=True)
yangin_istatistik.to_excel(r"C:\Users\terzi\Desktop\yangin_istatistik\2018\excel\yangin_sayi_ve_sebepleri_2018.xlsx" ,index=False ,header=True)