In [10]:
import pandas as pd
import numpy as np

In [11]:
yangin_istatistik = pd.read_csv(r"C:\Users\terzi\Desktop\TEMİZ\yangin_istatistik\2021\142_202203_2021yanginistatistik.csv" ,sep=";")

In [12]:
yangin_istatistik.head()

,ilceler,elk._kontak,lpg_d.gaz_vb.,ocak_sob._kalo._kaz.,baca_tut.,sig._ve_kibr.,akary.,pat._madd.,yıld._dus.,sabotaj,diger,anlasılamadı,tplm
0,SELÇUKLU,71,0,23,12,381,1,3,0,21,126,8,646
1,MERAM,86,1,53,11,348,1,7,0,28,100,9,644
2,KARATAY,72,0,32,6,389,2,2,0,27,113,17,660
3,SANCAK,41,3,6,3,176,0,2,0,9,53,4,297
4,AKÖREN,2,1,2,2,4,0,0,0,0,8,16,35

In [13]:
yangin_istatistik = yangin_istatistik.rename(columns={'elk._kontak': 'elektrik_kontagi', 'lpg_d.gaz_vb.': 'lpg/dogalgaz', 'ocak_sob._kalo._kaz.': 'ocak/soba/kalorifer/kazan', 'baca_tut.': 'baca_tutusmasi', 'sig._ve_kibr.': 'sigara/kibrit', 'akary.': 'akaryakit', 'pat._madd.': 'patlayici_madde', 'yıld._dus.': 'yildirim_dusmesi', 'anlasılamadı': 'anlasilamadi', 'tplm': 'toplam'})

In [14]:
yangin_istatistik.head()

,ilceler,elektrik_kontagi,lpg/dogalgaz,ocak/soba/kalorifer/kazan,baca_tutusmasi,sigara/kibrit,akaryakit,patlayici_madde,yildirim_dusmesi,sabotaj,diger,anlasilamadi,toplam
0,SELÇUKLU,71,0,23,12,381,1,3,0,21,126,8,646
1,MERAM,86,1,53,11,348,1,7,0,28,100,9,644
2,KARATAY,72,0,32,6,389,2,2,0,27,113,17,660
3,SANCAK,41,3,6,3,176,0,2,0,9,53,4,297
4,AKÖREN,2,1,2,2,4,0,0,0,0,8,16,35

In [15]:
a=yangin_istatistik["elektrik_kontagi"]
b=yangin_istatistik["lpg/dogalgaz"]
c=yangin_istatistik["ocak/soba/kalorifer/kazan"]
d=yangin_istatistik["baca_tutusmasi"]
e=yangin_istatistik["sigara/kibrit"]
f=yangin_istatistik["akaryakit"]
g=yangin_istatistik["patlayici_madde"]
h=yangin_istatistik["yildirim_dusmesi"]
i=yangin_istatistik["sabotaj"]
j=yangin_istatistik["diger"]
k=yangin_istatistik["anlasilamadi"]
l=yangin_istatistik["toplam"]

toplam_saglama=a+b+c+d+e+f+g+h+i+j+k==l
toplam_saglama.head(50)

0     True
1     True
2     True
3     True
4     True
5     True
6     True
7     True
8     True
9     True
10    True
11    True
12    True
13    True
14    True
15    True
16    True
17    True
18    True
19    True
20    True
21    True
22    True
23    True
24    True
25    True
26    True
27    True
28    True
dtype: bool

In [16]:
yangin_istatistik.to_csv(r"C:\Users\terzi\Desktop\yangin_istatistik\2021\csv\yangin_sayi_ve_sebepleri_2021.csv" ,index=False ,header=True)
yangin_istatistik.to_excel(r"C:\Users\terzi\Desktop\yangin_istatistik\2021\excel\yangin_sayi_ve_sebepleri_2021.xlsx" ,index=False ,header=True)